/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panda.JPanels;

/**
 *
 * @author Paperkoops
 */
public class FrmAdministracion extends javax.swing.JPanel {

    /**
     * Creates new form FrmAdministracion
     */
    public FrmAdministracion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        navAdministracion1 = new panda.JPanels.NavAdministracion();

        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Administracion");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 120, -1, -1));
        add(navAdministracion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private panda.JPanels.NavAdministracion navAdministracion1;
    // End of variables declaration//GEN-END:variables
}
