/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panda.JPanels;

import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.concurrent.TimeUnit;
import javafx.animation.ScaleTransition;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.paint.Color;
import javafx.scene.shape.Circle;
import javafx.util.Duration;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import panda.JFrames.Principal;
import panda.Panda;


/**
 *
 * @author Paperkoops
 */
public class FrmMenuPrincipal extends javax.swing.JPanel {

       // public boolean check;

    /**
     * Creates new form FrmMenuPrincipal
     */
    public FrmMenuPrincipal() {
        initComponents();
        jLabel2.setVisible(false);
        
    }
    //private int x = 390;
    //private int y = 190;
    //private int x = 0;
    //private int y = 0;
    // int size= 100;
@Override
  protected void paintComponent(Graphics g) {
BufferedImage bgImage = null;

        try {
            bgImage = ImageIO.read(new File("src/panda/Imagenes/MenuPrincipal/bk.png"));
        } catch (IOException e) {
            e.printStackTrace();
        }
    super.paintComponent(g);
        g.drawImage(bgImage, 0, 0, null);
        
        
        //g.fillOval(x, y, size, size);
                

         
}
 

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(77, 80, 87));
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panda/Imagenes/MenuPrincipal/trans2.gif"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panda/Imagenes/MenuPrincipal/btnPerfiles.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panda/Imagenes/MenuPrincipal/btnLaboratorios.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panda/Imagenes/MenuPrincipal/btnConsultas.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panda/Imagenes/MenuPrincipal/btnMiCuenta.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panda/Imagenes/MenuPrincipal/btnAdministracion.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panda/Imagenes/MenuPrincipal/btnEstadisticas.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panda/Imagenes/MenuPrincipal/icon3.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panda/Imagenes/MenuPrincipal/btnCerrarSesion.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
        try{
         ImageIcon papa =  new ImageIcon(ImageIO.read(new File("src/panda/Imagenes/MenuPrincipal/btnPerfiles-hover.png")));
         
        jLabel3.setIcon(papa);
        
        
        }catch(Exception e){
                JOptionPane.showMessageDialog(null, "yay no funciona", "InfoBox: " + "titulo", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // TODO add your handling code here:
         try{
         ImageIcon papa =  new ImageIcon(ImageIO.read(new File("src/panda/Imagenes/MenuPrincipal/btnPerfiles.png")));
         
        jLabel3.setIcon(papa);
        }catch(Exception e){
                JOptionPane.showMessageDialog(null, "yay no funciona", "InfoBox: " + "titulo", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        // TODO add your handling code here:
        try{
         ImageIcon papa =  new ImageIcon(ImageIO.read(new File("src/panda/Imagenes/MenuPrincipal/btnLaboratorios-hover.png")));
         
        jLabel4.setIcon(papa);
        }catch(Exception e){
                JOptionPane.showMessageDialog(null, "yay no funciona", "InfoBox: " + "titulo", JOptionPane.INFORMATION_MESSAGE);

        }
        
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        // TODO add your handling code here:
        try{
         ImageIcon papa =  new ImageIcon(ImageIO.read(new File("src/panda/Imagenes/MenuPrincipal/btnLaboratorios.png")));
         
        jLabel4.setIcon(papa);
        }catch(Exception e){
                JOptionPane.showMessageDialog(null, "yay no funciona", "InfoBox: " + "titulo", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        // TODO add your handling code here:
        try{
         ImageIcon papa =  new ImageIcon(ImageIO.read(new File("src/panda/Imagenes/MenuPrincipal/btnConsultas-hover.png")));
         
        jLabel5.setIcon(papa);
        }catch(Exception e){
                JOptionPane.showMessageDialog(null, "yay no funciona", "InfoBox: " + "titulo", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        // TODO add your handling code here:
        try{
         ImageIcon papa =  new ImageIcon(ImageIO.read(new File("src/panda/Imagenes/MenuPrincipal/btnConsultas.png")));
         
        jLabel5.setIcon(papa);
        }catch(Exception e){
                JOptionPane.showMessageDialog(null, "yay no funciona", "InfoBox: " + "titulo", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        // TODO add your handling code here:
        try{
         ImageIcon papa =  new ImageIcon(ImageIO.read(new File("src/panda/Imagenes/MenuPrincipal/btnMiCuenta-hover.png")));
         
        jLabel6.setIcon(papa);
        }catch(Exception e){
                JOptionPane.showMessageDialog(null, "yay no funciona", "InfoBox: " + "titulo", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        // TODO add your handling code here:
        try{
         ImageIcon papa =  new ImageIcon(ImageIO.read(new File("src/panda/Imagenes/MenuPrincipal/btnMiCuenta.png")));
         
        jLabel6.setIcon(papa);
        }catch(Exception e){
                JOptionPane.showMessageDialog(null, "yay no funciona", "InfoBox: " + "titulo", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        // TODO add your handling code here:
        try{
         ImageIcon papa =  new ImageIcon(ImageIO.read(new File("src/panda/Imagenes/MenuPrincipal/btnAdministracion-hover.png")));
         
        jLabel7.setIcon(papa);
        }catch(Exception e){
                JOptionPane.showMessageDialog(null, "yay no funciona", "InfoBox: " + "titulo", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        // TODO add your handling code here:
        try{
         ImageIcon papa =  new ImageIcon(ImageIO.read(new File("src/panda/Imagenes/MenuPrincipal/btnAdministracion.png")));
         
        jLabel7.setIcon(papa);
        }catch(Exception e){
                JOptionPane.showMessageDialog(null, "yay no funciona", "InfoBox: " + "titulo", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        // TODO add your handling code here:
         try{
         ImageIcon papa =  new ImageIcon(ImageIO.read(new File("src/panda/Imagenes/MenuPrincipal/btnEstadisticas-hover.png")));
         
        jLabel8.setIcon(papa);
        }catch(Exception e){
                JOptionPane.showMessageDialog(null, "yay no funciona", "InfoBox: " + "titulo", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        // TODO add your handling code here:
        try{
         ImageIcon papa =  new ImageIcon(ImageIO.read(new File("src/panda/Imagenes/MenuPrincipal/btnEstadisticas.png")));
         
        jLabel8.setIcon(papa);
        }catch(Exception e){
                JOptionPane.showMessageDialog(null, "yay no funciona", "InfoBox: " + "titulo", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
        // TODO add your handling code here:
        try{
         ImageIcon papa =  new ImageIcon(ImageIO.read(new File("src/panda/Imagenes/MenuPrincipal/btnCerrarSesion-hover.png")));
         
        jLabel10.setIcon(papa);
        }catch(Exception e){
                JOptionPane.showMessageDialog(null, "yay no funciona", "InfoBox: " + "titulo", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        // TODO add your handling code here:
        try{
         ImageIcon papa =  new ImageIcon(ImageIO.read(new File("src/panda/Imagenes/MenuPrincipal/btnCerrarSesion.png")));
         
        jLabel10.setIcon(papa);
        }catch(Exception e){
                JOptionPane.showMessageDialog(null, "yay no funciona", "InfoBox: " + "titulo", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_jLabel10MouseExited

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "yay entro");
        //CirculoUwU();
        
      
        jLabel2.setVisible(true);
        try {
            TimeUnit.SECONDS.wait(100000);
            JOptionPane.showMessageDialog(null, "yay espero");
        } catch (Exception e) {
        }
        
         
    }//GEN-LAST:event_jLabel4MouseClicked

    
    public void pausarelcoso(){
        timer.stop();
    }
    
    Timer timer = new Timer (1000, new ActionListener () 
{ 
    public void actionPerformed(ActionEvent e) 
    { 
        // Aquí el código que queramos ejecutar.
        //JOptionPane.showMessageDialog(null, "papapapapaap");
        panda.Panda.mamain.CambiarPanel(1);
        
        pausarelcoso();
     }
    
}); 
    
    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(null, "swiggity swoop");
        jLabel2.setVisible(true);
        timer.start();
        
        
        //panda.Panda.mamain.CambiarPanel();
        
    }//GEN-LAST:event_jLabel7MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
