/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panda.JPanels;

import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author B250M
 */
public class FrmMenuLaboratorio extends javax.swing.JPanel {

    /**
     * Creates new form FrmMenuLaboratorio
     */
    public FrmMenuLaboratorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1000, 600));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panda/Imagenes/MenuConsultas/Agregar NH.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panda/Imagenes/MenuConsultas/Atender NH.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panda/Imagenes/MenuConsultas/Consultar cola NH.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(67, 67, 67))
        );
    }// </editor-fold>//GEN-END:initComponents
    public ImageIcon AgregarH = null;
    public ImageIcon AgregarNH = null;
    public ImageIcon AtenderH = null;
    public ImageIcon AtenderNH = null;
    public ImageIcon ConsultarcolaH = null;
    public ImageIcon ConsultarcolaNH = null;
    
    
    private void CargarImagenes() {
        try {
            AgregarH = new ImageIcon(ImageIO.read(new File("src/panda/Imagenes/MenuCosultas/Agregar H.png")));
            AgregarNH = new ImageIcon(ImageIO.read(new File("src/panda/Imagenes/MenuCosultas/Agregar NH.png")));
            AtenderH = new ImageIcon(ImageIO.read(new File("src/panda/Imagenes/MenuCosultas/Atender H.png")));
            AtenderNH = new ImageIcon(ImageIO.read(new File("src/panda/Imagenes/MenuCosultas/Atender NH.png")));
            ConsultarcolaH = new ImageIcon(ImageIO.read(new File("src/panda/Imagenes/MenuCosultas/Consultar cola NH.png")));
            ConsultarcolaNH = new ImageIcon(ImageIO.read(new File("src/panda/Imagenes/MenuCosultas/Consultar cola NH.png")));
            

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "yay no funciona", "InfoBox: " + "titulo", JOptionPane.INFORMATION_MESSAGE);

        }
    }
    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
       
        try {
            jLabel2.setIcon(AtenderNH);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "yay no funciona", "InfoBox: " + "titulo", JOptionPane.INFORMATION_MESSAGE);

        }
             
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add your handling code here:
        try {
            jLabel2.setIcon(AtenderH);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "yay no funciona", "InfoBox: " + "titulo", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
        try {
            jLabel3.setIcon(ConsultarcolaH);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "yay no funciona", "InfoBox: " + "titulo", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // TODO add your handling code here:
        try {
            jLabel3.setIcon(ConsultarcolaNH);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "yay no funciona", "InfoBox: " + "titulo", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
        try {
            jLabel1.setIcon(AgregarH);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "yay no funciona", "InfoBox: " + "titulo", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
        try {
            jLabel1.setIcon(AgregarNH);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "yay no funciona", "InfoBox: " + "titulo", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_jLabel1MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
