/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panda.JPanels;

import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Paperkoops
 */
public class SideNav extends javax.swing.JPanel {

    /**
     * Creates new form SideNav
     */
    public SideNav() {
        initComponents();
        CargarImagenes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 51, 51));
        setPreferredSize(new java.awt.Dimension(200, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panda/Imagenes/SideNav/consultas.jpg"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
        });
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panda/Imagenes/SideNav/panda.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    public ImageIcon ImgPanda = null;
    public ImageIcon ImgConsultas = null;
    public ImageIcon ImgLaboratorios = null;
    public ImageIcon ImgEstadisticas = null;
    public ImageIcon ImgAdministracion = null;
    public ImageIcon ImgPerfiles = null;
    public ImageIcon ImgMiCuenta = null;
    public ImageIcon ImgCerrarCesion = null;
    
    public ImageIcon ImgPandaHover = null;
    public ImageIcon ImgConsultasHover = null;
    public ImageIcon ImgLaboratoriosHover = null;
    public ImageIcon ImgEstadisticasHover = null;
    public ImageIcon ImgAdministracionHover = null;
    public ImageIcon ImgPerfilesHover = null;
    public ImageIcon ImgMiCuentaHover = null;
    public ImageIcon ImgCerrarCesionHover = null;

    private void CargarImagenes() {
        try {
            ImgPanda = new ImageIcon(ImageIO.read(new File("src/panda/Imagenes/SideNav/btnTipoUsuario.png")));
            ImgConsultas = new ImageIcon(ImageIO.read(new File("src/panda/Imagenes/MenuAdministracion/btnTipoUsuario-hover.png")));
            ImgLaboratorios = new ImageIcon(ImageIO.read(new File("src/panda/Imagenes/MenuAdministracion/btnEnfermedades.png")));
            ImgEstadisticas = new ImageIcon(ImageIO.read(new File("src/panda/Imagenes/MenuAdministracion/btnEnfermedades-hover.png")));
            ImgAdministracion = new ImageIcon(ImageIO.read(new File("src/panda/Imagenes/MenuAdministracion/btnHospitalizacion.png")));
            ImgPerfiles = new ImageIcon(ImageIO.read(new File("src/panda/Imagenes/MenuAdministracion/btnHospitalizacion-hover.png")));
            ImgMiCuenta = new ImageIcon(ImageIO.read(new File("src/panda/Imagenes/MenuAdministracion/btnSintomas.png")));
            ImgCerrarCesion = new ImageIcon(ImageIO.read(new File("src/panda/Imagenes/MenuAdministracion/btnSintomas-hover.png")));
            
            
            ImgPanda = new ImageIcon(ImageIO.read(new File("src/panda/Imagenes/MenuAdministracion/btnTipoUsuario.png")));
            ImgConsultas = new ImageIcon(ImageIO.read(new File("src/panda/Imagenes/MenuAdministracion/btnTipoUsuario-hover.png")));
            ImgLaboratorios = new ImageIcon(ImageIO.read(new File("src/panda/Imagenes/MenuAdministracion/btnEnfermedades.png")));
            ImgEstadisticas = new ImageIcon(ImageIO.read(new File("src/panda/Imagenes/MenuAdministracion/btnEnfermedades-hover.png")));
            ImgAdministracion = new ImageIcon(ImageIO.read(new File("src/panda/Imagenes/MenuAdministracion/btnHospitalizacion.png")));
            ImgPerfiles = new ImageIcon(ImageIO.read(new File("src/panda/Imagenes/MenuAdministracion/btnHospitalizacion-hover.png")));
            ImgMiCuenta = new ImageIcon(ImageIO.read(new File("src/panda/Imagenes/MenuAdministracion/btnSintomas.png")));
            ImgCerrarCesion = new ImageIcon(ImageIO.read(new File("src/panda/Imagenes/MenuAdministracion/btnSintomas-hover.png")));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "yay no funciona", "InfoBox: " + "titulo", JOptionPane.INFORMATION_MESSAGE);

        }
    }
    
    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseEntered
//Cambiar area  panda.Panda.mamain.CambiarPanelDeArea(4);

//Cambiar en navegacion  panda.Panda.mamain.CambiarPanelEnNavegacion(2);

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
